# Generated by Django 3.0.4 on 2020-04-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('owned_by', models.CharField(max_length=100)),
                ('Engine_Brand', models.CharField(max_length=100)),
                ('Engine_Displacement', models.CharField(max_length=100)),
                ('Engine_Maximum_Output', models.CharField(max_length=100)),
                ('Engine_Type', models.CharField(max_length=100)),
                ('Engine_Oil_Alert_System', models.CharField(max_length=100)),
                ('Engine_Ignition_System', models.CharField(max_length=100)),
                ('Engine_Start', models.CharField(max_length=100)),
                ('Generator_Alternator', models.CharField(max_length=100)),
                ('Voltage_Regulator', models.CharField(max_length=100)),
                ('Phase', models.CharField(max_length=100)),
                ('ACMax_Output', models.CharField(max_length=100)),
                ('AC_Rated_Output', models.CharField(max_length=100)),
                ('Rated_Voltage', models.CharField(max_length=100)),
                ('DC_Output', models.CharField(max_length=100)),
                ('Rated_Power_Factor', models.CharField(max_length=100)),
                ('Pilot_Lamp', models.CharField(max_length=100)),
                ('Volt_Meter', models.CharField(max_length=100)),
                ('Fuel_Tank_Capacity', models.IntegerField()),
                ('Continuous_Operating_Hours', models.CharField(max_length=100)),
                ('Dimensions_L_W_H', models.CharField(max_length=100)),
                ('Dry_Weight', models.IntegerField()),
            ],
        ),
    ]
