# Generated by Django 3.0.4 on 2020-04-18 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0003_device_engine_supervisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfBirth', models.DateField()),
                ('phone', models.CharField(blank=True, help_text='Contact Phone Number', max_length=30)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('cnic', models.CharField(blank=True, max_length=20, null=True)),
                ('designation', models.CharField(max_length=50)),
                ('emp_delete', models.BooleanField(default=False)),
                ('emp_type', models.CharField(choices=[('Electrician', 'Electrician'), ('Mechanic', 'Mechanic'), ('Supervisor', 'Supervisor')], max_length=20)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Device')),
                ('emp_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_user', to=settings.AUTH_USER_MODEL)),
                ('emp_supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_supervisor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
