# Generated by Django 3.0.4 on 2020-04-19 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0005_auto_20200419_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading', models.IntegerField()),
                ('status', models.CharField(choices=[('1', 'Assigned'), ('2', 'Under Process'), ('3', 'Completed')], max_length=30)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Device')),
                ('emp_on_duty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_emp_on_duty', to=settings.AUTH_USER_MODEL)),
                ('emp_supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_emp_supervisor', to=settings.AUTH_USER_MODEL)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Sensors')),
            ],
        ),
    ]
