# Generated by Django 3.0.4 on 2020-04-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensors',
            name='max_reading',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('1', 'Created'), ('2', 'Assigned'), ('3', 'Under Process'), ('4', 'Completed')], max_length=30),
        ),
    ]
