# Generated by Django 3.0.4 on 2020-04-17 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_detail_sku', models.CharField(blank=True, max_length=50, null=True)),
                ('order_detail_quantity', models.IntegerField()),
                ('order_detail_price', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('customer_phone', models.CharField(max_length=20)),
                ('shipping_address', models.TextField()),
                ('order_cost', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('received', 'received'), ('acknowledged', 'acknowledged'), ('deleivered', 'deleivered')], default='received', max_length=12)),
                ('order_detail', models.ManyToManyField(blank=True, null=True, to='orders.OrderDetail')),
            ],
        ),
    ]
